#****** Applications DB ******#
applications_db: 
  data_path: /data/1-original/applicationsDB/
  output_path: /data/2-decomposed/temp_applicationsDB/
  pdf-txt: True
  pdf-img: True
  starting_subfolder: GANCELL - UNPROCESSED
  
#****** Companies DB ******#
companies_db: 
  data_path: /data/1-original/companiesDB/
  output_path: /data/2-decomposed/companiesDB/

#****** Definitions DB ******#
definitions_db: 
  data_path: /data/1-original/definitionsDB/definitionsDB.docx
  output_path: /data/2-decomposed/definitionsDB/definitionsDB.csv