
config_dir: /gpfs01/home/efykr2/MetroLLM/modelDev-textClass-A/config.yaml

train:
  data:
    source_dir: /gpfs01/home/efykr2/MetroLLM/data/3-formatted/textClass/textClass-applicationsDB-train.csv
    task_col: Task
    text_col: Text
    class_no: 21
  
  model:
    name: answerdotai/ModernBERT-large
    max_length: 8192
    
  training_args:
    output_dir                  : /gpfs01/home/efykr2/MetroLLM/modelDev-textClass-A/results/
    learning_rate               : 2e-5
    per_device_train_batch_size : 1
    per_device_eval_batch_size  : 1
    gradient_accumulation_steps : 16
    num_train_epochs            : 3
    gradient_checkpointing      : True
    warmup_ratio                : 0.1
    weight_decay                : 0.01
    eval_strategy               : "epoch"
    save_strategy               : "epoch"
    save_total_limit            : 3
    metric_for_best_model       : "f1_micro"
    load_best_model_at_end      : True
    logging_dir                 : modelDev-textClass-A/results/
    logging_steps               : 50
    bf16                        : True
    push_to_hub                 : False
    
    log_training_steps:   True

eval:
  data: 
    source_dir: /gpfs01/home/efykr2/MetroLLM/data/3-formatted/textClass/textClass-applicationsDB-test.csv
    class_no: 21

  model:
    source_dir: 
