# config.yaml
# Containing arguments for training and evaluation processes.


config_dir: /gpfs01/home/efykr2/MetroLLM/modelDev-textClass-A/config.yaml

#*** TRAIN CONFIG ***#
train:
  data:
    source_dir: /gpfs01/home/efykr2/MetroLLM/data/3-formatted/textClass/textClass-applicationsDB-train.csv
    task_col: Task
    text_col: Text
    class_no: 21
  
  model:
    name: answerdotai/ModernBERT-base # answerdotai/ModernBERT-large
    max_length: 8192
    
  training_args:
    #*- Transformers Training Arguments -*#
    output_dir                  : /gpfs01/home/efykr2/MetroLLM/modelDev-textClass-A/results/
    learning_rate               : 8e-7
    per_device_train_batch_size : 4
    per_device_eval_batch_size  : 4
    gradient_accumulation_steps : 1
    num_train_epochs            : 3
    gradient_checkpointing      : True
    warmup_ratio                : 0.1
    weight_decay                : 0.1
    eval_strategy               : "steps"
    eval_steps                  : 12
    save_strategy               : "steps"
    save_steps                  : 12
    logging_strategy            : "steps"
    logging_steps               : 12
    save_total_limit            : 8
    metric_for_best_model       : "f1_micro"
    load_best_model_at_end      : True
    logging_dir                 : modelDev-textClass-A/results/
    logging_steps               : 10
    bf16                        : True
    push_to_hub                 : False
    save_safetensors            : True
    max_grad_norm               : 0.1
    lr_scheduler_type           : cosine
    label_smoothing_factor      : 0.1
    
    #*- Other -*#
    dropout: 0.3
    log_training_steps:   True


#*** EVALUATE CONFIG ***#
eval:
  data: 
    source_dir: /Users/kieranrudd/Library/CloudStorage/OneDrive-TheUniversityofNottingham/MetroLLM/data/3-formatted/textClass/textClass-applicationsDB-test.csv
    task_col: Task
    text_col: Text
    class_no: 21

  model:
    name: answerdotai/ModernBERT-base
    source_dir: /Users/kieranrudd/Library/CloudStorage/OneDrive-TheUniversityofNottingham/MetroLLM/modelDev-textClass-A/results/models/base/checkpoint-248/
    max_length: 8192
  
  training_args:
    dropout: 0.1
    
  evaluation_args:
    output_dir: /Users/kieranrudd/Library/CloudStorage/OneDrive-TheUniversityofNottingham/MetroLLM/modelDev-textClass-A/results/evaluations/
    batch_size: 1
