# NB: add '/' at the start of directories for ensured directory formatting

train:
  data:
    dir: "./data/3-formatted/t2tGen/t2tGen_train.csv"
    task_col: "task"
    input_col: "input"
    output_col: "output"
    max_seq_length: 256

  model:
    name: "google/flan-t5-large"
    max_input_length: 256
    max_target_length: 256

  training_args:
    output_dir: "./modelDev-text2textGen/results"
    log_dir: "./modelDev-text2textGen/results/logs.csv"
    lr: 3e-4
    epochs: 5
    batch_size: 4
    eval_batch_size: 4
    weight_decay: 0.01
    save_total_limit: 3
    metric_for_best_model: "eval_rouge1"



eval:
  data:
    dir: "./data/3-formatted/t2tGen/archive/t2tGen_test.csv"
    task_col: "task"
    input_col: "input"
    output_col: "output"
    max_seq_length: 256

  model:
    dir: "./modelDev-text2textGen/results/checkpoint-67320"
    max_input_length: 256
    max_target_length: 256

  eval_args:
    metric: "rouge"
    batch_size: 8
    output_dir: "./modelDev-text2textGen/results/eval_results.json"
