#****** Applications DB ******#
run_applications_db: False
applications_db: 
  data_path: /data/applicationsDB/original
  output_path: /data/applicationsDB/new
  
  pdf-txt: True # To convert PDFs text to .txt files.
  pdf-img: True # To pull images from PDFs as .png.
  
  debug: False # Useful for extended outputs. 

#****** Definitions DB ******#
run_definitions_db: True
definitions_db: 
  data_path: data/definitionsDB/original/definitions.docx
  output_path: data/definitionsDB/new/definitions.csv
  
  debug: False 

#****** Companies DB ******#
run_companies_db: False
companies_db: 
  data_path: data/original/companies
  output_path: data/new/companies
  
  debug: False
